

[env:test_native]
platform = native
build_type = test
build_flags =
  -std=gnu++2a
  -D IS_TESTING
  -I test/include ;for lv_conf.h
  -D TILECACHE_SIZE=20
test_framework = googletest
lib_deps =
  googletest
  lvgl/lvgl @ 9.5.0
  bitbank2/PNGdec @ ^1.0.3 ; instead of stblib, works with less memory
  https://github.com/t413/esp32-stb-image ; fork to allow native testing. used for PNG writing
lib_compat_mode = off ;allows PNGdec library
; build_src_filter =
;   +<test/main.cpp>
test_build_src = yes
